# Theme Settings
remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dirt"

# Site Settings
locale                   : "ko-KR"
rtl                      :
title                    : "haran-dev-archive"
title_separator          : "|"
subtitle                 :
name                     : "신하란"
description              : "신하란의 블로그입니다."
url        : "https://haranshin.github.io"
baseurl    : "/haran-dev-archive.io"
repository : "HaranShin/haran-dev-archive.io"
teaser                   :
logo                     : "/assets/images/shr_usagi.jpg"
masthead_title           :
breadcrumbs              :
words_per_minute         : 200
enable_copy_code_button  : true
copyright                :
copyright_url            :

# SEO Related
naver_site_verification  : "04f423db5824d897696d39311c1f8728439dee76"

# Site Author
author:
  avatar           : "/assets/images/office.jpg"
  bio              : ""
  location         : 
  email            :
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/HaranShin"
  since: "2026"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - README.md
  - docs
  - test          # <--- 추가! (테스트 포스트 제외)
  - CHANGELOG.md    # <--- 추가! (마크다운 하이라이트 구문 에러 파일 제외)

keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Asia/Seoul

# Pagination
paginate: 5
paginate_path: /page:num/

# Plugins (GitHub Pages 공식 지원 플러그인만 유지)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives (Liquid 기본 방식 적용)
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
      toc: true
      toc_sticky: true
      toc_label: "On this page"
      sidebar:
        nav: "sidebar_main"

date_format: "%Y-%m-%d"